name: Run CI/CD
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: "1" # Enable color output, even though the console output is redirected in Actions
  TERM: xterm # Enable color output in GitHub Actions
on: [push]
jobs:
  mcp:
    runs-on: ubuntu-latest
    name: MCP (dotnet 9)
    services:
      rabbitmq:
        image: rabbitmq:3.8-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        # needed because the rabbitmq container does not provide a healthcheck
        options: >-
          --health-cmd "rabbitmqctl node_health_check" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore src/mcp.test
      - name: Unit Tests
        run: dotnet test --no-restore --no-build -c Release src/mcp.test

  #########
  #
  # Release

  calc-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    needs:
      - mcp
    if: github.ref == 'refs/heads/main'
    outputs:
      version: ${{ steps.version-bump-git-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - id: version-bump-git-tag
        name: Bump version and push git tag
        uses: anothrNick/github-tag-action@1.53.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: release

  #########
  #
  # Publish
  
  publish-docker:
    runs-on: ubuntu-latest
    name: Publish Docker Image (GitHub)
    needs:
      - calc-version
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build the docker image to confirm its happy
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: ./src
          push: true
          tags: ghcr.io/messageaid/mcp:latest
          cache-from: type=registry,ref=ghcr.io/messageaid/mcp:latest
          cache-to: type=inline
